import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { AlertTriangle, ArrowRight, Boxes, ClipboardCheck, FileWarning, Users } from 'lucide-react'
import { getSession, type Session } from '../../services/auth.service'
import { apiFetch } from '../../services/api'

type Customer = { id: string; name: string; orders_count: number }
type Product = { id: string; name: string; stock_quantity: string; min_stock_quantity: string; status: string }
type Order = { id: string; customer_name: string; status: string; total_amount: string; created_at: string }
type Quote = { id: string; customer_name: string; status: string; valid_until: string; total_amount: string }

export function DashboardPage() {
  const [session, setSession] = useState<Session | null>(null); const [customers, setCustomers] = useState<Customer[]>([]); const [products, setProducts] = useState<Product[]>([]); const [orders, setOrders] = useState<Order[]>([]); const [quotes, setQuotes] = useState<Quote[]>([]); const [error, setError] = useState('')
  useEffect(() => { Promise.all([getSession(), apiFetch<Customer[]>('/api/customers'), apiFetch<Product[]>('/api/products'), apiFetch<Order[]>('/api/orders'), apiFetch<Quote[]>('/api/quotes')]).then(([me, customerList, productList, orderList, quoteList]) => { setSession(me); setCustomers(customerList); setProducts(productList); setOrders(orderList); setQuotes(quoteList) }).catch((requestError) => setError(requestError instanceof Error ? requestError.message : 'Não foi possível carregar o Radar.')) }, [])
  const firstName = session?.full_name.split(' ')[0] || 'gestor'
  const radar = useMemo(() => { const criticalProducts = products.filter((product) => product.status === 'Esgotado' || product.status === 'Estoque baixo' || Number(product.stock_quantity) <= Number(product.min_stock_quantity)); const inProduction = orders.filter((order) => order.status === 'in_preparation'); const today = new Date(); const expiringQuotes = quotes.filter((quote) => quote.status === 'pending' && (new Date(`${quote.valid_until}T00:00:00`).getTime() - today.getTime()) <= 7 * 86400000); const revenue = orders.filter((order) => order.status === 'completed').reduce((total, order) => total + Number(order.total_amount), 0); return { criticalProducts, inProduction, expiringQuotes, revenue } }, [products, orders, quotes])
  const priorities = [{ label: 'Estoque crítico', detail: radar.criticalProducts.length ? `${radar.criticalProducts.length} produto(s) precisam de reposição.` : 'Nenhum item em nível crítico.', href: '/produtos', icon: AlertTriangle, tone: radar.criticalProducts.length ? 'text-[#c77716] bg-[#fff8eb]' : 'text-[#32866a] bg-[#effbf6]' }, { label: 'Pedidos em produção', detail: radar.inProduction.length ? `${radar.inProduction.length} pedido(s) aguardando preparo.` : 'A fila de produção está vazia.', href: '/pedidos', icon: ClipboardCheck, tone: 'text-signal bg-[#f2f5ff]' }, { label: 'Orçamentos próximos do vencimento', detail: radar.expiringQuotes.length ? `${radar.expiringQuotes.length} orçamento(s) precisam de acompanhamento.` : 'Nenhum orçamento pendente próximo do vencimento.', href: '/orcamentos', icon: FileWarning, tone: 'text-[#8b5cc7] bg-[#f8f2ff]' }]
  return <div className="page-wrap"><header className="page-header"><div><p className="eyebrow">Radar operacional</p><h1>Olá, {firstName}.</h1><p>Veja prioridades e indicadores reais da sua empresa.</p></div><div className="flex flex-wrap gap-3"><Link className="secondary-button" to="/clientes/novo">Cadastrar cliente</Link><Link className="secondary-button" to="/produtos/novo">Cadastrar produto</Link><Link className="primary-button" to="/copiloto">Abrir Copiloto</Link></div></header>{error && <p className="error-banner">{error}</p>}<section className="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4"><RadarCard icon={Users} label="Clientes" value={customers.length} detail="base cadastrada" href="/clientes" /><RadarCard icon={Boxes} label="Produtos" value={products.length} detail="itens no catálogo" href="/produtos" /><RadarCard icon={ClipboardCheck} label="Em produção" value={radar.inProduction.length} detail="pedidos aguardando preparo" href="/pedidos" /><RadarCard icon={FileWarning} label="Faturamento concluído" value={`R$ ${radar.revenue.toFixed(2).replace('.', ',')}`} detail="pedidos concluídos" href="/pedidos" /></section><section className="mt-6 grid gap-5 lg:grid-cols-[minmax(0,1.35fr)_minmax(300px,.65fr)]"><div className="page-card"><div className="mb-5 flex items-start justify-between"><div><p className="eyebrow">Prioridades</p><h2 className="font-display text-xl font-semibold">O que precisa da sua atenção</h2></div><span className="rounded-full bg-[#f2f5ff] px-3 py-2 text-xs font-bold text-signal">{priorities.filter((item) => item.label !== 'Pedidos em produção' || radar.inProduction.length > 0).length} alertas</span></div><div className="grid gap-3">{priorities.map(({ label, detail, href, icon: Icon, tone }) => <Link className="flex items-center gap-3 rounded-lg border border-line p-4 no-underline transition hover:border-[#9fb5ff]" key={label} to={href}><span className={`grid h-10 w-10 shrink-0 place-items-center rounded-lg ${tone}`}><Icon size={19} /></span><span className="min-w-0 flex-1"><strong className="block text-sm text-ink">{label}</strong><small className="mt-1 block text-xs text-muted">{detail}</small></span><ArrowRight className="text-[#8991aa]" size={17} /></Link>)}</div></div><div className="page-card"><div className="mb-5"><p className="eyebrow">Acesso rápido</p><h2 className="font-display text-xl font-semibold">Operação manual</h2><p className="mt-2 text-xs leading-relaxed text-muted">Escolha como trabalhar. O Copiloto é opcional.</p></div><div className="grid gap-2.5"><QuickLink href="/clientes" label="Gerenciar clientes" /><QuickLink href="/produtos" label="Gerenciar produtos" /><QuickLink href="/orcamentos" label="Criar orçamento" /><QuickLink href="/pedidos" label="Acompanhar pedidos" /></div></div></section></div>
}

function RadarCard({ icon: Icon, label, value, detail, href }: { icon: typeof Users; label: string; value: number | string; detail: string; href: string }) { return <Link className="group rounded-[10px] border border-line bg-white p-5 no-underline shadow-[0_8px_24px_rgba(17,25,54,.04)] transition hover:-translate-y-0.5 hover:border-[#9fb5ff]" to={href}><span className="mb-4 grid h-9 w-9 place-items-center rounded-lg bg-[#f2f5ff] text-signal"><Icon size={18} /></span><span className="block text-xs text-muted">{label}</span><strong className="mt-1 block font-display text-2xl font-semibold text-ink">{value}</strong><small className="mt-1 block text-[11px] text-[#8991aa]">{detail}</small></Link> }
function QuickLink({ href, label }: { href: string; label: string }) { return <Link className="flex items-center justify-between rounded-lg border border-line px-3.5 py-3 text-xs font-bold text-[#354064] no-underline hover:border-[#9fb5ff] hover:text-signal" to={href}>{label}<ArrowRight size={15} /></Link> }
