import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { apiFetch } from '../../services/api'

type Order = { id: string; customer_name: string; status: string; items: { product_name: string; quantity: string }[]; created_at: string }

export function FactoryModePage() {
  const [orders, setOrders] = useState<Order[]>([]); const [tab, setTab] = useState('in_preparation'); const [status, setStatus] = useState('Atualizando produção...')
  async function load() { try { setOrders(await apiFetch<Order[]>('/api/orders')); setStatus('') } catch (error) { setStatus(error instanceof Error ? error.message : 'Não foi possível carregar a produção.') } }
  useEffect(() => { apiFetch<Order[]>('/api/orders').then((list) => { setOrders(list); setStatus('') }).catch((error) => setStatus(error instanceof Error ? error.message : 'Não foi possível carregar a produção.')) }, [])
  async function complete(order: Order) { try { const updated = await apiFetch<Order>(`/api/orders/${order.id}`, { method: 'PATCH', body: JSON.stringify({ status: 'completed' }) }); setOrders((current) => current.map((item) => item.id === order.id ? updated : item)) } catch (error) { setStatus(error instanceof Error ? error.message : 'Não foi possível concluir o pedido.') } }
  const visible = orders.filter((order) => order.status === tab)
  const pendingItems = orders.filter((order) => order.status === 'in_preparation').reduce((total, order) => total + order.items.reduce((sum, item) => sum + Number(item.quantity), 0), 0)
  return <div className="page-wrap factory-page"><header className="page-header"><div><p className="eyebrow">Gestoria / Produção</p><h1>Modo Fábrica</h1><p>Organize a fila de preparo e conclua os pedidos em produção.</p></div><Link className="secondary-button" to="/dashboard">Voltar ao painel</Link></header><div className="metric-grid"><article><span>Na produção</span><strong>{orders.filter((order) => order.status === 'in_preparation').length}</strong></article><article><span>Itens pendentes</span><strong>{pendingItems}</strong></article><article><span>Concluídos</span><strong>{orders.filter((order) => order.status === 'completed').length}</strong></article></div><section className="page-card"><div className="factory-tabs"><button className={tab === 'in_preparation' ? 'active' : ''} onClick={() => setTab('in_preparation')}>Em produção</button><button className={tab === 'completed' ? 'active' : ''} onClick={() => setTab('completed')}>Concluídos</button><button className="secondary-button" onClick={() => void load()}>Atualizar</button></div>{status && <p className="table-status">{status}</p>}{!status && <div className="factory-orders">{visible.map((order) => <article className="factory-order" key={order.id}><div><p className="eyebrow">Pedido {order.id.slice(0, 8)}</p><h2>{order.customer_name}</h2><p>{order.items.map((item) => `${item.quantity}x ${item.product_name}`).join(' · ')}</p></div>{tab === 'in_preparation' && <button className="primary-button" onClick={() => void complete(order)}>Marcar concluído</button>}</article>)}{visible.length === 0 && <p className="table-status">Nenhum pedido nesta fila.</p>}</div>}</section></div>
}
