"""Fiscal order integrity and historical snapshots.

Revision ID: 0006_fiscal_integrity
Revises: 0005_fiscal_documents

PostgreSQL only, matching the deployment database. Existing records are retained
as legacy. Ambiguous duplicates/tenant links abort the transaction before DDL.
"""

import sqlalchemy as sa

from alembic import op

revision = "0006_fiscal_integrity"
down_revision = "0005_fiscal_documents"
branch_labels = None
depends_on = None

PREFLIGHT_SQL = """
DO $$ BEGIN
    IF EXISTS (
        SELECT 1 FROM fiscal_documents WHERE document_type = 'saida'
        AND order_id IS NOT NULL AND status IN ('Autorizada', 'Em processamento')
        GROUP BY organization_id, order_id HAVING COUNT(*) > 1
    ) THEN
        RAISE EXCEPTION 'Fiscal preflight: multiple active outgoing documents per order. Reconcile records before retrying; no record was deleted.';
    END IF;
    IF EXISTS (
        SELECT 1 FROM fiscal_documents WHERE document_type = 'saida'
        GROUP BY organization_id, model, series, number HAVING COUNT(*) > 1
    ) THEN
        RAISE EXCEPTION 'Fiscal preflight: duplicate outgoing number/series/model. Review the fiscal history before retrying.';
    END IF;
    IF EXISTS (
        SELECT 1 FROM fiscal_documents f LEFT JOIN orders o ON o.id = f.order_id
        LEFT JOIN customers c ON c.id = o.customer_id
        WHERE f.order_id IS NOT NULL AND
        (f.document_type = 'entrada' OR o.id IS NULL OR o.organization_id <> f.organization_id
         OR c.organization_id <> f.organization_id)
    ) THEN
        RAISE EXCEPTION 'Fiscal preflight: invalid or cross-tenant order link. Correct the association under review before retrying.';
    END IF;
END $$;
"""


def upgrade():
    if op.get_bind().dialect.name != "postgresql":
        raise RuntimeError(
            "This migration requires PostgreSQL; SQLite is used only by ORM unit tests."
        )
    # Run during a maintenance window: prevent concurrent writes while checking/backfilling.
    op.execute(
        "LOCK TABLE fiscal_documents, orders, customers, products IN SHARE ROW EXCLUSIVE MODE"
    )
    op.execute(PREFLIGHT_SQL)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "suppliers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("document", sa.String(length=18), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id", "document", name="uq_suppliers_org_document"
        ),
        sa.UniqueConstraint("organization_id", "id", name="uq_suppliers_org_id"),
    )
    op.create_index(
        "ix_suppliers_org_name", "suppliers", ["organization_id", "name"], unique=False
    )
    op.create_unique_constraint("uq_orders_org_id", "orders", ["organization_id", "id"])
    op.create_unique_constraint(
        "uq_customers_org_id", "customers", ["organization_id", "id"]
    )
    op.create_unique_constraint(
        "uq_products_org_id", "products", ["organization_id", "id"]
    )
    op.add_column(
        "fiscal_documents", sa.Column("customer_id", sa.Uuid(), nullable=True)
    )
    op.add_column(
        "fiscal_documents", sa.Column("supplier_id", sa.Uuid(), nullable=True)
    )
    op.add_column(
        "fiscal_documents", sa.Column("created_by_id", sa.Uuid(), nullable=True)
    )
    op.add_column(
        "fiscal_documents", sa.Column("updated_by_id", sa.Uuid(), nullable=True)
    )
    op.add_column(
        "fiscal_documents",
        sa.Column("authorized_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "fiscal_documents",
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "fiscal_documents",
        sa.Column("authorization_protocol", sa.String(length=120), nullable=True),
    )
    op.add_column(
        "fiscal_documents",
        sa.Column("cancellation_protocol", sa.String(length=120), nullable=True),
    )
    op.add_column(
        "fiscal_documents",
        sa.Column("cancellation_reason", sa.String(length=500), nullable=True),
    )
    op.add_column(
        "fiscal_documents",
        sa.Column(
            "is_legacy", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    op.add_column(
        "fiscal_documents",
        sa.Column(
            "snapshot_source",
            sa.String(length=30),
            server_default="legacy_unverified",
            nullable=False,
        ),
    )
    op.add_column(
        "fiscal_documents",
        sa.Column("reconciled_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "fiscal_documents",
        sa.Column("stock_received_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.execute("UPDATE fiscal_documents SET is_legacy = true")
    op.drop_constraint("fiscal_documents_order_id_fkey", "fiscal_documents")
    op.drop_constraint("fiscal_documents_organization_id_fkey", "fiscal_documents")
    op.drop_constraint("fiscal_documents_access_key_key", "fiscal_documents")
    op.create_foreign_key(
        "fk_fiscal_created_by_id",
        "fiscal_documents",
        "users",
        ["created_by_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        "fk_fiscal_updated_by_id",
        "fiscal_documents",
        "users",
        ["updated_by_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_check_constraint(
        "ck_fiscal_authorization_evidence",
        "fiscal_documents",
        "is_legacy OR status != 'Autorizada' OR (authorized_at IS NOT NULL AND authorization_protocol IS NOT NULL)",
    )
    op.create_check_constraint(
        "ck_fiscal_cancellation_evidence",
        "fiscal_documents",
        "is_legacy OR status != 'Cancelada' OR (cancelled_at IS NOT NULL AND cancellation_reason IS NOT NULL)",
    )
    op.create_check_constraint(
        "ck_fiscal_dates_order",
        "fiscal_documents",
        "authorized_at IS NULL OR cancelled_at IS NULL OR cancelled_at >= authorized_at",
    )
    op.create_check_constraint(
        "ck_fiscal_direction_links",
        "fiscal_documents",
        "(document_type = 'entrada' AND order_id IS NULL AND customer_id IS NULL) OR (document_type = 'saida' AND supplier_id IS NULL)",
    )
    op.create_check_constraint(
        "ck_fiscal_required_links",
        "fiscal_documents",
        "is_legacy OR (created_by_id IS NOT NULL AND updated_by_id IS NOT NULL AND ((document_type = 'saida' AND order_id IS NOT NULL AND customer_id IS NOT NULL) OR (document_type = 'entrada' AND supplier_id IS NOT NULL)))",
    )
    op.create_foreign_key(
        "fk_fiscal_customer_org",
        "fiscal_documents",
        "customers",
        ["organization_id", "customer_id"],
        ["organization_id", "id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        "fk_fiscal_order_org",
        "fiscal_documents",
        "orders",
        ["organization_id", "order_id"],
        ["organization_id", "id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        "fk_fiscal_organization",
        "fiscal_documents",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        "fk_fiscal_supplier_org",
        "fiscal_documents",
        "suppliers",
        ["organization_id", "supplier_id"],
        ["organization_id", "id"],
        ondelete="RESTRICT",
    )
    op.create_unique_constraint(
        "uq_fiscal_documents_org_id", "fiscal_documents", ["organization_id", "id"]
    )
    op.create_unique_constraint(
        "uq_fiscal_org_access_key",
        "fiscal_documents",
        ["organization_id", "access_key"],
    )
    op.create_index(
        "ix_fiscal_org_number",
        "fiscal_documents",
        ["organization_id", "number"],
        unique=False,
    )
    op.create_index(
        "ix_fiscal_org_order",
        "fiscal_documents",
        ["organization_id", "order_id"],
        unique=False,
    )
    op.create_index(
        "ix_fiscal_org_status",
        "fiscal_documents",
        ["organization_id", "status"],
        unique=False,
    )
    op.create_index(
        "uq_fiscal_active_order",
        "fiscal_documents",
        ["organization_id", "order_id"],
        unique=True,
        postgresql_where=sa.text(
            "document_type = 'saida' AND order_id IS NOT NULL AND status IN ('Autorizada', 'Em processamento')"
        ),
        sqlite_where=sa.text(
            "document_type = 'saida' AND order_id IS NOT NULL AND status IN ('Autorizada', 'Em processamento')"
        ),
    )
    op.create_index(
        "uq_fiscal_incoming_number",
        "fiscal_documents",
        ["organization_id", "supplier_id", "model", "series", "number"],
        unique=True,
        postgresql_where=sa.text(
            "document_type = 'entrada' AND supplier_id IS NOT NULL"
        ),
        sqlite_where=sa.text("document_type = 'entrada' AND supplier_id IS NOT NULL"),
    )
    op.create_index(
        "uq_fiscal_outgoing_number",
        "fiscal_documents",
        ["organization_id", "model", "series", "number"],
        unique=True,
        postgresql_where=sa.text("document_type = 'saida'"),
        sqlite_where=sa.text("document_type = 'saida'"),
    )
    op.create_table(
        "fiscal_document_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("product_name", sa.String(length=160), nullable=False),
        sa.Column("unit_of_measure", sa.String(length=20), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("total", sa.Numeric(precision=18, scale=5), nullable=False),
        sa.Column("fiscal_snapshot", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "quantity > 0 AND unit_price >= 0 AND total >= 0",
            name="ck_fiscal_item_values",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "document_id"],
            ["fiscal_documents.organization_id", "fiscal_documents.id"],
            name="fk_fiscal_item_document_org",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "product_id"],
            ["products.organization_id", "products.id"],
            name="fk_fiscal_item_product_org",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "id", name="uq_fiscal_items_org_id"),
    )
    op.create_index(
        "ix_fiscal_items_org_document",
        "fiscal_document_items",
        ["organization_id", "document_id"],
        unique=False,
    )
    op.create_table(
        "fiscal_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=False),
        sa.Column("action", sa.String(length=40), nullable=False),
        sa.Column("detail", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["organization_id", "document_id"],
            ["fiscal_documents.organization_id", "fiscal_documents.id"],
            name="fk_fiscal_event_document_org",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_fiscal_events_org_document",
        "fiscal_events",
        ["organization_id", "document_id"],
        unique=False,
    )
    op.create_table(
        "fiscal_stock_movements",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("item_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=False),
        sa.Column("movement_type", sa.String(length=20), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(movement_type = 'receipt' AND quantity > 0) OR (movement_type = 'reversal' AND quantity < 0)",
            name="ck_fiscal_stock_sign",
        ),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["organization_id", "document_id"],
            ["fiscal_documents.organization_id", "fiscal_documents.id"],
            name="fk_fiscal_stock_document_org",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "item_id"],
            ["fiscal_document_items.organization_id", "fiscal_document_items.id"],
            name="fk_fiscal_stock_item_org",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "product_id"],
            ["products.organization_id", "products.id"],
            name="fk_fiscal_stock_product_org",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "item_id", "movement_type", name="uq_fiscal_stock_item_type"
        ),
    )
    op.create_index(
        "ix_fiscal_stock_org_document",
        "fiscal_stock_movements",
        ["organization_id", "document_id"],
        unique=False,
    )


def downgrade():
    # Never silently discard snapshots, audit events, receipts or new links.
    op.execute("""DO $$ BEGIN
        IF EXISTS (SELECT 1 FROM fiscal_events)
           OR EXISTS (SELECT 1 FROM fiscal_document_items)
           OR EXISTS (SELECT 1 FROM fiscal_stock_movements)
           OR EXISTS (SELECT 1 FROM suppliers)
           OR EXISTS (SELECT 1 FROM fiscal_documents WHERE NOT is_legacy OR reconciled_at IS NOT NULL)
        THEN RAISE EXCEPTION 'Fiscal downgrade blocked: new fiscal data exists. Restore a reviewed backup instead of dropping history.';
        END IF;
    END $$;""")
    op.drop_table("fiscal_stock_movements")
    op.drop_table("fiscal_events")
    op.drop_table("fiscal_document_items")
    for name in [
        "uq_fiscal_active_order",
        "uq_fiscal_outgoing_number",
        "uq_fiscal_incoming_number",
        "ix_fiscal_org_number",
        "ix_fiscal_org_order",
        "ix_fiscal_org_status",
    ]:
        op.drop_index(name, table_name="fiscal_documents")
    for name in [
        "fk_fiscal_order_org",
        "fk_fiscal_customer_org",
        "fk_fiscal_supplier_org",
        "fk_fiscal_organization",
        "fk_fiscal_created_by_id",
        "fk_fiscal_updated_by_id",
        "ck_fiscal_required_links",
        "ck_fiscal_direction_links",
        "ck_fiscal_dates_order",
        "ck_fiscal_authorization_evidence",
        "ck_fiscal_cancellation_evidence",
        "uq_fiscal_org_access_key",
        "uq_fiscal_documents_org_id",
    ]:
        op.drop_constraint(name, "fiscal_documents")
    for name in [
        "customer_id",
        "supplier_id",
        "created_by_id",
        "updated_by_id",
        "authorized_at",
        "cancelled_at",
        "authorization_protocol",
        "cancellation_protocol",
        "cancellation_reason",
        "is_legacy",
        "snapshot_source",
        "reconciled_at",
        "stock_received_at",
    ]:
        op.drop_column("fiscal_documents", name)
    op.create_foreign_key(
        "fiscal_documents_organization_id_fkey",
        "fiscal_documents",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fiscal_documents_order_id_fkey",
        "fiscal_documents",
        "orders",
        ["order_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_unique_constraint(
        "fiscal_documents_access_key_key", "fiscal_documents", ["access_key"]
    )
    op.drop_table("suppliers")
    for table in ["orders", "customers", "products"]:
        op.drop_constraint(f"uq_{table}_org_id", table)
