"""add organization profile fields

Revision ID: 20796917ffea
Revises: cbd36bd2ca60
Create Date: 2026-09-02 19:38:41.465465
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '20796917ffea'
down_revision: Union[str, None] = 'cbd36bd2ca60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('document', sa.String(length=18), nullable=True))
    op.add_column('organizations', sa.Column('state_registration', sa.String(length=30), nullable=True))
    op.add_column('organizations', sa.Column('municipal_registration', sa.String(length=30), nullable=True))
    op.add_column('organizations', sa.Column('phone', sa.String(length=30), nullable=True))
    op.add_column('organizations', sa.Column('postal_code', sa.String(length=9), nullable=True))
    op.add_column('organizations', sa.Column('street', sa.String(length=160), nullable=True))
    op.add_column('organizations', sa.Column('number', sa.String(length=20), nullable=True))
    op.add_column('organizations', sa.Column('complement', sa.String(length=80), nullable=True))
    op.add_column('organizations', sa.Column('neighborhood', sa.String(length=80), nullable=True))
    op.add_column('organizations', sa.Column('city', sa.String(length=80), nullable=True))
    op.add_column('organizations', sa.Column('state', sa.String(length=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'state')
    op.drop_column('organizations', 'city')
    op.drop_column('organizations', 'neighborhood')
    op.drop_column('organizations', 'complement')
    op.drop_column('organizations', 'number')
    op.drop_column('organizations', 'street')
    op.drop_column('organizations', 'postal_code')
    op.drop_column('organizations', 'phone')
    op.drop_column('organizations', 'municipal_registration')
    op.drop_column('organizations', 'state_registration')
    op.drop_column('organizations', 'document')
    # ### end Alembic commands ###
