"""add customer profile fields

Revision ID: cbd36bd2ca60
Revises: d2a10c3ad5ef
Create Date: 2026-09-02 13:09:00.714505
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cbd36bd2ca60'
down_revision: Union[str, None] = 'd2a10c3ad5ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('person_type', sa.String(length=10), nullable=False, server_default='individual'))
    op.add_column('customers', sa.Column('document', sa.String(length=18), nullable=True))
    op.add_column('customers', sa.Column('trade_name', sa.String(length=120), nullable=True))
    op.add_column('customers', sa.Column('state_registration', sa.String(length=30), nullable=True))
    op.add_column('customers', sa.Column('whatsapp', sa.String(length=30), nullable=True))
    op.add_column('customers', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('customers', sa.Column('birth_date', sa.Date(), nullable=True))
    op.add_column('customers', sa.Column('category', sa.String(length=20), nullable=False, server_default='final_consumer'))
    op.add_column('customers', sa.Column('default_discount_percent', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('customers', sa.Column('notes', sa.String(length=1000), nullable=True))
    op.add_column('customers', sa.Column('postal_code', sa.String(length=9), nullable=True))
    op.add_column('customers', sa.Column('street', sa.String(length=160), nullable=True))
    op.add_column('customers', sa.Column('number', sa.String(length=20), nullable=True))
    op.add_column('customers', sa.Column('complement', sa.String(length=80), nullable=True))
    op.add_column('customers', sa.Column('neighborhood', sa.String(length=80), nullable=True))
    op.add_column('customers', sa.Column('city', sa.String(length=80), nullable=True))
    op.add_column('customers', sa.Column('state', sa.String(length=2), nullable=True))
    op.create_check_constraint('ck_customer_category', 'customers', "category IN ('final_consumer', 'reseller', 'event')")
    op.create_check_constraint('ck_customer_discount_range', 'customers', 'default_discount_percent >= 0 AND default_discount_percent <= 100')
    op.create_check_constraint('ck_customer_person_type', 'customers', "person_type IN ('individual', 'company')")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_customer_person_type', 'customers', type_='check')
    op.drop_constraint('ck_customer_discount_range', 'customers', type_='check')
    op.drop_constraint('ck_customer_category', 'customers', type_='check')
    op.drop_column('customers', 'state')
    op.drop_column('customers', 'city')
    op.drop_column('customers', 'neighborhood')
    op.drop_column('customers', 'complement')
    op.drop_column('customers', 'number')
    op.drop_column('customers', 'street')
    op.drop_column('customers', 'postal_code')
    op.drop_column('customers', 'notes')
    op.drop_column('customers', 'default_discount_percent')
    op.drop_column('customers', 'category')
    op.drop_column('customers', 'birth_date')
    op.drop_column('customers', 'email')
    op.drop_column('customers', 'whatsapp')
    op.drop_column('customers', 'state_registration')
    op.drop_column('customers', 'trade_name')
    op.drop_column('customers', 'document')
    op.drop_column('customers', 'person_type')
    # ### end Alembic commands ###
