"""add quotes and quote items tables

Revision ID: d2a10c3ad5ef
Revises: 0003
Create Date: 2026-08-31 13:43:41.108513
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd2a10c3ad5ef'
down_revision: Union[str, None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('converted_order_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'approved', 'rejected', 'converted')", name='ck_quote_status'),
    sa.CheckConstraint('total_amount >= 0', name='ck_quote_total_nonnegative'),
    sa.ForeignKeyConstraint(['converted_order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_quotes_org_created_at', 'quotes', ['organization_id', 'created_at'], unique=False)
    op.create_index('ix_quotes_org_customer', 'quotes', ['organization_id', 'customer_id'], unique=False)
    op.create_index('ix_quotes_org_status_created_at', 'quotes', ['organization_id', 'status', 'created_at'], unique=False)
    op.create_table('quote_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('quote_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_quote_item_quantity_positive'),
    sa.CheckConstraint('unit_price >= 0', name='ck_quote_item_price_nonnegative'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_quote_items_product_id', 'quote_items', ['product_id'], unique=False)
    op.create_index('ix_quote_items_quote_id', 'quote_items', ['quote_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_quote_items_quote_id', table_name='quote_items')
    op.drop_index('ix_quote_items_product_id', table_name='quote_items')
    op.drop_table('quote_items')
    op.drop_index('ix_quotes_org_status_created_at', table_name='quotes')
    op.drop_index('ix_quotes_org_customer', table_name='quotes')
    op.drop_index('ix_quotes_org_created_at', table_name='quotes')
    op.drop_table('quotes')
    # ### end Alembic commands ###
