import { useEffect, useState } from 'react'
import type { FormEvent } from 'react'
import { Link, useNavigate, useSearchParams } from 'react-router-dom'
import { apiFetch } from '../../services/api'

type Customer = Record<string, string | number | null | undefined> & { id: string }
const initialForm = { name: '', phone: '', person_type: 'individual', document: '', trade_name: '', state_registration: '', whatsapp: '', email: '', birth_date: '', category: 'final_consumer', default_discount_percent: '', notes: '', postal_code: '', street: '', number: '', complement: '', neighborhood: '', city: '', state: '' }
const fields = [['name', 'Nome completo / Razão social'], ['phone', 'Telefone'], ['document', 'CPF / CNPJ'], ['trade_name', 'Nome fantasia'], ['state_registration', 'Inscrição estadual'], ['whatsapp', 'WhatsApp'], ['email', 'E-mail'], ['birth_date', 'Data de nascimento'], ['default_discount_percent', 'Desconto padrão (%)'], ['postal_code', 'CEP'], ['street', 'Rua'], ['number', 'Número'], ['complement', 'Complemento'], ['neighborhood', 'Bairro'], ['city', 'Cidade'], ['state', 'Estado (UF)']] as const

export function CustomerFormPage() {
  const navigate = useNavigate(); const [params] = useSearchParams(); const id = params.get('id'); const [form, setForm] = useState(initialForm); const [status, setStatus] = useState(''); const [loading, setLoading] = useState(Boolean(id))
  useEffect(() => { if (!id) return; apiFetch<Customer[]>('/api/customers').then((list) => { const customer = list.find((item) => item.id === id); if (customer) setForm(Object.fromEntries(Object.keys(initialForm).map((key) => [key, customer[key] == null ? '' : String(customer[key])])) as typeof initialForm) }).catch((error) => setStatus(error instanceof Error ? error.message : 'Não foi possível carregar o cliente.')).finally(() => setLoading(false)) }, [id])
  function update(field: keyof typeof initialForm, value: string) { setForm((current) => ({ ...current, [field]: value })) }
  async function submit(event: FormEvent) { event.preventDefault(); setStatus(''); if (!form.name.trim() || !form.phone.trim()) { setStatus('Nome e telefone são obrigatórios.'); return } try { const payload = { ...form, email: form.email || null, birth_date: form.birth_date || null, default_discount_percent: form.default_discount_percent ? form.default_discount_percent.replace(',', '.') : null, ...Object.fromEntries(['document', 'trade_name', 'state_registration', 'whatsapp', 'notes', 'postal_code', 'street', 'number', 'complement', 'neighborhood', 'city', 'state'].map((key) => [key, form[key as keyof typeof initialForm] || null])) }; await apiFetch(id ? `/api/customers/${id}` : '/api/customers', { method: id ? 'PATCH' : 'POST', body: JSON.stringify(payload) }); navigate('/clientes') } catch (error) { setStatus(error instanceof Error ? error.message : 'Não foi possível salvar o cliente.') } }
  if (loading) return <div className="page-wrap"><p className="table-status">Carregando cliente...</p></div>
  return <div className="page-wrap"><header className="page-header"><div><p className="eyebrow">Cadastro manual</p><h1>{id ? 'Editar cliente' : 'Novo cliente'}</h1><p>Preencha todos os dados comerciais, pessoais e de endereço.</p></div><Link className="secondary-button" to="/clientes">Voltar para clientes</Link></header><form className="page-card grid gap-6" onSubmit={submit}><div className="grid gap-4 md:grid-cols-3"><label className="form-label">Tipo de pessoa<select className="form-input" value={form.person_type} onChange={(event) => update('person_type', event.target.value)}><option value="individual">Pessoa física</option><option value="company">Pessoa jurídica</option></select></label>{fields.slice(0, 5).map(([field, label]) => <label className="form-label" key={field}>{label}<input className="form-input" type={field === 'email' ? 'email' : 'text'} value={form[field]} onChange={(event) => update(field, event.target.value)} required={field === 'name' || field === 'phone'} /></label>)}</div><div className="border-t border-line pt-5"><p className="eyebrow">Contato e relacionamento</p><div className="grid gap-4 md:grid-cols-3">{fields.slice(5, 9).map(([field, label]) => <label className="form-label" key={field}>{label}<input className="form-input" type={field === 'email' ? 'email' : field === 'birth_date' ? 'date' : 'text'} value={form[field]} onChange={(event) => update(field, event.target.value)} /></label>)}<label className="form-label md:col-span-3">Observações<textarea className="form-input min-h-24" value={form.notes} onChange={(event) => update('notes', event.target.value)} /></label></div></div><div className="border-t border-line pt-5"><p className="eyebrow">Endereço</p><div className="grid gap-4 md:grid-cols-4">{fields.slice(9).map(([field, label]) => <label className={`form-label ${field === 'street' ? 'md:col-span-2' : ''}`} key={field}>{label}<input className="form-input" value={form[field]} onChange={(event) => update(field, event.target.value)} /></label>)}</div></div>{status && <p className="form-status">{status}</p>}<div className="flex flex-wrap gap-3"><button className="primary-button" type="submit">Salvar cliente</button><Link className="secondary-button" to="/clientes">Cancelar</Link></div></form></div>
}
