import { useEffect, useState } from 'react'
import type { FormEvent } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import { apiFetch } from '../../services/api'

type Product = { id: string; name: string; price: string; category: string; stock_quantity: string }
export function ProductFormPage() {
	const [params] = useSearchParams(); const id = params.get('id'); const [name, setName] = useState(''); const [price, setPrice] = useState(''); const [category, setCategory] = useState('outros'); const [stock, setStock] = useState('0'); const [status, setStatus] = useState('')
	useEffect(() => { if (id) apiFetch<Product[]>('/api/products').then((list) => { const product = list.find((item) => item.id === id); if (product) { setName(product.name); setPrice(String(product.price)); setCategory(product.category); setStock(String(product.stock_quantity)) } }) }, [id])
	async function submit(event: FormEvent) { event.preventDefault(); setStatus(''); const numericPrice = Number(price.replace(',', '.')); if (!name.trim() || numericPrice <= 0) { setStatus('Informe nome e preço válido.'); return } try { const payload = { name, price: numericPrice, category, stock_quantity: Number(stock.replace(',', '.')) || 0 }; await apiFetch(id ? `/api/products/${id}` : '/api/products', { method: id ? 'PATCH' : 'POST', body: JSON.stringify(payload) }); setStatus('Produto salvo com sucesso.') } catch (error) { setStatus(error instanceof Error ? error.message : 'Não foi possível salvar.') } }
	return <div className="page-wrap"><header className="page-header"><div><p className="eyebrow">Catálogo</p><h1>{id ? 'Editar produto' : 'Novo produto'}</h1><p>Controle preços e estoque em um só lugar.</p></div><Link className="secondary-button" to="/dashboard">Voltar</Link></header><form className="page-card form-card" onSubmit={submit}><label>Nome<input value={name} onChange={(event) => setName(event.target.value)} /></label><label>Preço<input inputMode="decimal" value={price} onChange={(event) => setPrice(event.target.value)} /></label><label>Categoria<select value={category} onChange={(event) => setCategory(event.target.value)}><option value="padaria">Padaria</option><option value="frios">Frios</option><option value="bebidas">Bebidas</option><option value="outros">Outros</option></select></label><label>Estoque<input inputMode="decimal" value={stock} onChange={(event) => setStock(event.target.value)} /></label>{status && <p className="form-status">{status}</p>}<button className="primary-button" type="submit">Salvar produto</button></form></div>
}
